services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiMDllMzM5Mzk3YmJlMzAyY2Q1MTEwODAzZThiZDNiYjAiLCJ0IjoiODVjYmNmYWUtMTkzNS00OWM5LTg1NTUtODkwZTVkODgxMGQ5IiwicyI6Ik1UWXlZekJqTkRjdE5XRmtaUzAwWkRrNExXSXhNVFl0WVdaak5XUXpaREptTWpKbCJ9
    depends_on:
      - caserna
      - caserna_db
      - grafana
    networks:
      - caserna_net

  caserna_db:
    image: postgres:14-alpine
    container_name: caserna_db
    environment:
      POSTGRES_USER: greg
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: caserna
      TZ: 'Europe/Madrid'
    restart: unless-stopped
    ports:
      - "10995:5432"
    volumes:
      - ~/db_data:/var/lib/postgresql/data:Z
    networks:
      - caserna_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U greg -d caserna -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  caserna:
    image: caserna:latest
    container_name: caserna
    privileged: true
    restart: unless-stopped
    environment:
      UPLOAD_TO_ADAFRUIT: 'False'
      TZ: 'Europe/Madrid'
    depends_on:
      - caserna_db
    networks:
      - caserna_net

  grafana:
    image: caserna_grafana:latest
    container_name: caserna_grafana
    ports:
      - "3000:3000"
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: caserna_db
      GF_DATABASE_PORT: 10995
      GF_DATABASE_NAME: caserna
      GF_DATABASE_USER: greg
      GF_DATABASE_PASSWORD: 1234
      GF_SECURITY_ADMIN_USER: greg
      GF_SECURITY_ADMIN_PASSWORD: 1234
      TZ: 'Europe/Madrid'
    depends_on:
      - caserna_db
    volumes:
      - ~/grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - caserna_net

networks:
  caserna_net:
    driver: host
