{
 "title": "Latest Weather Data",
 "description": "Latest Weather Data",
 "tags": [ "Caserna" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", Value AS \"Temperature\" FROM temperature ORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", Value AS \"Humidity\" FROM humidity ORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", Value AS \"Wind Speed\" FROM wind_speed ORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", Value AS \"Wind Direction\" FROM wind_direction ORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Light",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", Value AS \"Light\" FROM light ORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", Value AS \"Rain\" FROM rain ORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "hPa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", Value AS \"Pressure\" FROM pressure ORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  }
 ]
}