{
 "title": "Time Dashboard",
 "description": "Weather Data Collection",
 "tags": [ "Caserna" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", value AS \"Temperature\" FROM temperature ORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", value AS \"Humidity\" FROM humidity ORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", value AS \"Wind Speed\" FROM wind_speed ORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", value AS \"Wind Direction\" FROM wind_direction ORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", value AS \"Rain\" FROM rain ORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", value AS \"Light\" FROM light ORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "hPa" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", value AS \"Pressure\" FROM pressure ORDER BY timestamp;"
    }
   ]
  }
 ]
}